DROP DATABASE qlvt;
CREATE DATABASE qlvt;
USE qlvt;

CREATE TABLE VAITRO(
	MAQUYEN NCHAR(3) PRIMARY KEY NOT NULL,
    TENQUYEN NVARCHAR(15)
);
CREATE TABLE CHINHANH(
	MACN NCHAR(10) PRIMARY KEY NOT NULL,
    TEN NVARCHAR(100),
    DIACHI NVARCHAR(100),
    SDT NVARCHAR(15)
);
CREATE TABLE VATTU(
	MAVT NCHAR(4) PRIMARY KEY NOT NULL,
    TENVT NVARCHAR(20),
    DONVITINH NVARCHAR(10),
    SOLUONGTON INT
);
CREATE TABLE CTDDH(
	MADDH NCHAR(8) NOT NULL,
    MAVT NCHAR(4) NOT NULL,
    SOLUONG INT,
    DONGIA FLOAT,
    FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT),
    CONSTRAINT PK_CTDDH PRIMARY KEY (MADDH,MAVT)
);
CREATE TABLE CTPN(
	MAPN NCHAR(4) NOT NULL,
    MAVT NCHAR(4) NOT NULL,
    SOLUONG INT,
    DONGIA FLOAT,
    FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT),
    CONSTRAINT PK_CTPN PRIMARY KEY (MAPN,MAVT)
);
CREATE TABLE CTPX(
	MAPX NCHAR(4) NOT NULL,
    MAVT NCHAR(4) NOT NULL,
    SOLUONG INT,
    DONGIA FLOAT,
    FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT),
    CONSTRAINT PK_CTPX PRIMARY KEY (MAPX,MAVT)
);
CREATE TABLE KHO(
	MAKHO NCHAR(4) NOT NULL PRIMARY KEY,
    TENKHO NVARCHAR(30),
    DIACHI NVARCHAR(100),
    MACN NCHAR(10) NOT NULL,
    FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN)
);
CREATE TABLE NHANVIEN(
	MANV INT PRIMARY KEY NOT NULL,
    HOTEN NVARCHAR(40),
    SOCMND NVARCHAR(20),
    DIACHI NVARCHAR(100),
    NGAYSINH DATE,
    MATKHAU NCHAR(20),
    LUONG INT,
    MACN NCHAR(10) NOT NULL,
    MAQUYEN NCHAR(3),
    TRANGTHAI BIT,
    FOREIGN KEY (MAQUYEN) REFERENCES VAITRO(MAQUYEN),
    FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN)
);
CREATE TABLE DATHANG(
	MADDH NCHAR(8) PRIMARY KEY NOT NULL,
    NGAY DATE,
    NHACC NVARCHAR(100),
    MANV INT NOT NULL,
    MAKHO NCHAR(4) NOT NULL,
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
CREATE TABLE PHIEUNHAP(
	MAPN NCHAR(4) PRIMARY KEY NOT NULL,
    NGAY DATE,
	MADDH NCHAR(8),
    MANV INT NOT NULL,
    MAKHO NCHAR(4) NOT NULL,
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO)
);
CREATE TABLE PHIEUXUAT(
	MAPX NCHAR(4) PRIMARY KEY NOT NULL,
    NGAY DATE,
    HOTENKH NVARCHAR(20),
    MANV INT NOT NULL,
    MAKHO NCHAR(4) NOT NULL,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO)
);
INSERT INTO vaitro (MAQUYEN,TENQUYEN) VALUES ('Q01', 'Cong Ty');
INSERT INTO vaitro (MAQUYEN,TENQUYEN) VALUES ('Q02', 'Chi Nhanh');
INSERT INTO vaitro (MAQUYEN,TENQUYEN) VALUES ('Q03', 'Nhan Vien');
INSERT INTO chinhanh (MACN,TEN, DIACHI, SDT) VALUES ('CN01', 'Ha Noi', '12O Quang Trung Hoan Kiem','0123456789');
INSERT INTO nhanvien (MANV, HOTEN, SOCMND,DIACHI,NGAYSINH,LUONG,MATKHAU,MACN,MAQUYEN,TRANGTHAI) VALUES (1,'Bui Xuan Tu','036201001464','30 Quang Trung Hoan Kiem',20011111,2000,'123','CN01','Q03',0);
INSERT INTO vattu (MAVT,TENVT,DONVITINH,SOLUONGTON) VALUES ('LG01', 'Ti vi LG 24 inch', 'Cai',10);
INSERT INTO kho (MAKHO, TENKHO, DIACHI, MACN) VALUES ('HN01', 'Kho Hoan Kiem', '55 Ho Giang Vo','CN01');
INSERT INTO dathang (MADDH,NGAY,NHACC,MANV,MAKHO) VALUES ('DH01', 20230905, 'LG Viet Nam',1,'HN01');
INSERT INTO ctddh (MADDH,MAVT,SOLUONG,DONGIA) VALUES ('DH01', 'LG01', 10,1000);
